# Generated by Django 4.1.3 on 2022-12-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productgallery_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='market_price',
        ),
        migrations.AddField(
            model_name='product',
            name='our_price',
            field=models.IntegerField(null=True),
        ),
    ]
