# Generated by Django 4.1.3 on 2022-12-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_price_product_market_price_product_our_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/products'),
        ),
    ]
